### ISSUE TITLE
How to install it in debian server?

### ISSUE THREAD

**Issue by ikexue** [Caojiahao-Coder/gpt_next#21]
How to install it in debian server，is there any detailed instruction?

**Comment by Caojiahao-Coder** [comment]
I'm very sorry, I haven't used a Debian server.
However, I think you can start by using `npm run build` to package the project into the `dist ` folder. Then deploy it via nginx. (Because that's how I did it on my centos server).

<hr/>

In this project, I used a proxy service to accomplish the functionality needed for `function calling`. I can open-source it if you want. 🤝

**Comment by ikexue** [comment]
thank you very much,i will try

**Comment by Caojiahao-Coder** [comment]
<strong>Thank you for using it!</strong>

I have open-sourced the proxy service: https://github.com/Caojiahao-Coder/gptnext_proxy

>This is a Nuxt project that you can deploy using Vercel, but you need to register an Api Token with OpenWeather API that has Function Calling enabled.
