### ISSUE TITLE
https://groq.gptnext.chat/openai/v1/ is  down

### ISSUE THREAD

**Issue by tianshuo** [Caojiahao-Coder/gpt_next#28]
Cannot access

**Comment by Caojiahao-Coder** [comment]
Thanks for the feedback, I'll restore the service.

**Comment by Caojiahao-Coder** [comment]
**The proxy service was inaccessible due to server expiration. The current proxy service has now been restored.**

---

![image](https://github.com/user-attachments/assets/e23fb442-4938-4d42-9655-3ac71dfe756c)

![image](https://github.com/user-attachments/assets/131ed8c0-ef0d-45f0-8508-ab5cb6fcb3a8)

**Comment by tianshuo** [comment]
Thank you!!!
